---
- name: copy conf files before upgrade
  hosts: vap_servers
  gather_facts: no
  tasks:
     - name: Fetch the files
       fetch: dest=/etc/ansible/playbooks/uk3/vap/{{ item }}/ src=/usr/local/etc/kamailio/kamailio.cfg flat=true validate_checksum=true
       with_inventory_hostnames:
          - vap_servers
       when: inventory_hostname == "{{ item }}"
     - name: Fetch .conf files
       fetch: dest=/etc/ansible/playbooks/uk3/vap/{{ item }}/ src=/etc/asterisk/http.conf flat=true validate_checksum=true
       with_inventory_hostnames:
          - vap_servers
       when: inventory_hostname == "{{ item }}"
     - name: fetch
       fetch: dest=/etc/ansible/playbooks/uk3/vap/{{ item }}/ src=/opt/mcp/config/scheduler.yml flat=true validate_checksum=true
       with_inventory_hostnames:
          - vap_servers
       when: inventory_hostname == "{{ item }}"
     - name: fetch the files
       fetch: dest=/etc/ansible/playbooks/uk3/vap/{{ item }}/ src=/opt/mcp/config/ha.yml flat=true validate_checksum=true
       with_inventory_hostnames:
          - vap_servers
       when: inventory_hostname == "{{ item }}"
     - name: fetch the files
       fetch: dest=/etc/ansible/playbooks/uk3/vap/{{ item }}/  src=/etc/asterisk/manager.conf flat=true validate_checksum=true
       with_inventory_hostnames:
          - vap_servers
       when: inventory_hostname == "{{ item }}"
     - name: fetch the files
       fetch: dest=/etc/ansible/playbooks/uk3/vap/{{ item }}/ src=/opt/mcp/courier/conf/mmail.conf flat=true validate_checksum=true
       with_inventory_hostnames:
          - vap_servers
       when: inventory_hostname == "{{ item }}"
     - name: fetch the files
       fetch: dest=/etc/ansible/playbooks/uk3/vap/{{ item }}/ src=/opt/mcp/config/pgbouncer.ini flat=true validate_checksum=true
       with_inventory_hostnames:
          - vap_servers
       when: inventory_hostname == "{{ item }}"
     - name: Fetch first regex_groups file
       fetch: dest=/etc/ansible/playbooks/uk3/vap/{{ item }}/ src=/usr/local/etc/kamailio/regex_groups flat=true validate_checksum=true
       with_inventory_hostnames:
          - vap_servers
       when: inventory_hostname == "{{ item }}"
     - name: Fetch first regex_groups file
       fetch: dest=/etc/ansible/playbooks/uk3/vap/{{ item }}/ src=/etc/sysconfig/ha/lvs.cf flat=true validate_checksum=true
       with_inventory_hostnames:
          - vap_servers
       when: inventory_hostname == "{{ item }}"
