---
- name: copy conf files before upgrade
  hosts: mas1
  gather_facts: no
  tasks:
    
     - name: check disk space
       shell: df
       register: disk
     - name: print disk
       debug:
         msg: "{{ disk }}"

#       COPY THE CONF FILES

     - name: Fetch .conf files
       fetch: dest=/root/config/before_upgrade/mas1/http.conf src=/etc/asterisk/http.conf flat=true validate_checksum=true
     - name: fetch 
       fetch: dest=/root/config/before_upgrade/mas1/scheduler.yml src=/opt/mcp/config/scheduler.yml flat=true validate_checksum=true
     - name: fetch the files
       fetch: dest=/root/config/before_upgrade/mas1/ha.yml src=/opt/mcp/config/ha.yml flat=true validate_checksum=true
     - name: fetch the files
       fetch: dest=/root/config/before_upgrade/mas1/indications.conf  src=/etc/asterisk/indications.conf flat=true validate_checksum=true
     - name: fetch the files
       fetch: dest=/root/config/before_upgrade/mas1/manager.conf  src=/etc/asterisk/manager.conf flat=true validate_checksum=true
     - name: fetch the files
       fetch: dest=/root/config/before_upgrade/mas1/mmail.conf src=/opt/mcp/courier/conf/mmail.conf flat=true validate_checksum=true
     - name: fetch the files
       fetch: dest=/root/config/before_upgrade/mas1/pgbouncer.ini src=/opt/mcp/config/pgbouncer.ini flat=true validate_checksum=true
     - name: fetch the files
       fetch: dest=/root/config/before_upgrade/mas1/sms_gateway.yml src=/opt/mcp/config/sms_gateway.yml flat=true validate_checksum=true
     - name: fetch the files
       fetch: dest=/root/config/before_upgrade/mas1/smsMcpKannel.conf src=/opt/mcp/sms_receiver/config/smsMcpKannel.conf flat=true validate_checksum=true
     - name: fetch the files
       fetch: dest=/root/config/before_upgrade/mas1/sip.conf src=/etc/asterisk/sip.conf flat=true validate_checksum=true
     - name: Fetch first mcp.yml file
       fetch: dest=/root/config/before_upgrade/mas1/mcp.yml src=/opt/mcp/oamp-gui/config/mcp.yml flat=true validate_checksum=true                                                                                                                                                              
- hosts: db1
  gather_facts: yes
  become: yes
  tasks:
     - name: fetch the conf file
       fetch: dest=/root/config/before_upgrade/db1/ src=/opt/cdrtool/etc/etl.conf flat=true validate_checksum=true
     - name: fetch the files
       fetch: dest=/root/config/before_upgrade/db1/ src=/opt/mcp/config/sms.conf flat=true validate_checksum=true
     - name: fetch
       fetch: dest=/root/config/before_upgrade/db1/ src=/opt/mcp/config/scheduler.yml flat=true validate_checksum=true
     - name: fetch the files
       fetch: dest=/root/config/before_upgrade/db1/ src=/opt/mcp/config/ha.yml flat=true validate_checksum=true
     - name: fetch the files
       fetch: dest=/root/config/before_upgrade/db1/ src=/opt/mcp/courier/conf/mmail.conf flat=true validate_checksum=true
     - name: fetch the files
       fetch: dest=/root/config/before_upgrade/db1/ src=/opt/mcp/config/pgbouncer.ini flat=true validate_checksum=true
     - name: fetch the files
       fetch: dest=/root/config/before_upgrade/db1/ src=/opt/mcp/config/sms_gateway.yml flat=true validate_checksum=true
     - name: fetch the files
       fetch: dest=/root/config/before_upgrade/db1/ src=/opt/mcp/sms_receiver/config/smsMcpKannel.conf flat=true validate_checksum=true
- hosts: cdb
  gather_facts: yes
  become: yes
  tasks:
     - name: fetch the conf file
       fetch: dest=/root/config/before_upgrade/cdb/ src=/opt/cdrtool/etc/etl.conf flat=true validate_checksum=true
     - name: fetch the files
       fetch: dest=/root/config/before_upgrade/cdb/ src=/opt/mcp/config/sms.conf flat=true validate_checksum=true
     - name: fetch
       fetch: dest=/root/config/before_upgrade/cdb/ src=/opt/mcp/config/scheduler.yml flat=true validate_checksum=true
     - name: fetch the files
       fetch: dest=/root/config/before_upgrade/cdb/ src=/opt/mcp/config/ha.yml flat=true validate_checksum=true
     - name: fetch the files
       fetch: dest=/root/config/before_upgrade/cdb/ src=/opt/mcp/courier/conf/mmail.conf flat=true validate_checksum=true
     - name: fetch the files
       fetch: dest=/root/config/before_upgrade/cdb/ src=/opt/mcp/config/pgbouncer.ini flat=true validate_checksum=true
     - name: fetch the files
       fetch: dest=/root/config/before_upgrade/cdb/ src=/opt/mcp/config/sms_gateway.yml flat=true validate_checksum=true
     - name: fetch the files
       fetch: dest=/root/config/before_upgrade/cdb/ src=/opt/mcp/sms_receiver/config/smsMcpKannel.conf flat=true validate_checksum=true
- name: Compare regex_groups file Playbook
  hosts: vap_servers
  gather_facts: true

  tasks:
     - name: Fetch first regex_groups file
       fetch: dest=/root/config/before_upgrade/vap/ src=/usr/local/etc/kamailio/regex_groups flat=true validate_checksum=true
     - name: Fetch .conf files
       fetch: dest=/root/config/before_upgrade/vap/ src=/etc/asterisk/http.conf flat=true validate_checksum=true
     - name: fetch 
       fetch: dest=/root/config/before_upgrade/vap/ src=/opt/mcp/config/scheduler.yml flat=true validate_checksum=true
     - name: fetch the files
       fetch: dest=/root/config/before_upgrade/vap/ src=/opt/mcp/config/ha.yml flat=true validate_checksum=true
     - name: fetch the files
       fetch: dest=/root/config/before_upgrade/vap/ src=/etc/asterisk/indications.conf flat=true validate_checksum=true
     - name: fetch the files
       fetch: dest=/root/config/before_upgrade/vap/  src=/etc/asterisk/manager.conf flat=true validate_checksum=true
     - name: fetch the files
       fetch: dest=/root/config/before_upgrade/vap/ src=/opt/mcp/courier/conf/mmail.conf flat=true validate_checksum=true
     - name: fetch the files
       fetch: dest=/root/config/before_upgrade/vap/ src=/opt/mcp/config/pgbouncer.ini flat=true validate_checksum=true
     - name: fetch the files
       fetch: dest=/root/config/before_upgrade/vap/ src=/opt/mcp/config/sms_gateway.yml flat=true validate_checksum=true
     - name: fetch the files
       fetch: dest=/root/config/before_upgrade/vap/ src=/opt/mcp/sms_receiver/config/smsMcpKannel.conf flat=true validate_checksum=true
     - name: fetch the files
       fetch: dest=/root/config/before_upgrade/vap/ src=/etc/asterisk/sip.conf flat=true validate_checksum=true                                              


