---
- name: copy conf files before upgrade
  hosts: mas1
  gather_facts: no
  tasks:


#       COPY THE CONF FILES

     - name: Fetch .conf files
       fetch: dest=/root/config/before_upgrade/mas1/ src=/etc/asterisk/http.conf flat=true validate_checksum=true
     - name: fetch
       fetch: dest=/root/config/before_upgrade/mas1/ src=/opt/mcp/config/scheduler.yml flat=true validate_checksum=true
     - name: fetch the files
       fetch: dest=/root/config/before_upgrade/mas1/ha.yml src=/opt/mcp/config/ha.yml flat=true validate_checksum=true
     - name: fetch the files
       fetch: dest=/root/config/before_upgrade/mas1/indications.conf  src=/etc/asterisk/indications.conf flat=true validate_checksum=true
