# This playbook compares a specific file from two different hosts
# Example usage: ansible-playbook compare_manager.conf.yml

---
- name: Compare manager.conf file Playbook
  hosts: mas1_ip
  gather_facts: true

  tasks:
  - name: Fetch first manager.conf file
    fetch: dest=save/mas1_ip/manager.conf src=/etc/asterisk/manager.conf flat=true validate_checksum=true

- hosts: mas2_ip
  gather_facts: true

  tasks:
  - name: Fetch second manager.conf file
    fetch: dest=save/mas2_ip/manager.conf src=/etc/asterisk/manager.conf flat=true validate_checksum=true

- hosts: cm1
  gather_facts: true

  tasks:
  - name: 'Compare manager.conf files'
    command: 
      diff /etc/ansible/playbooks/monitor/save/mas1_ip/manager.conf /etc/ansible/playbooks/monitor/save/mas2_ip/manager.conf
      chdir=/etc/ansible/logs
    register: difference
    failed_when: difference.rc > 1
    changed_when: difference.rc == 1

  - name: Print differences
    debug: msg='{{ difference.stdout }}'

  - name: Create output file
    local_action: copy content='{{ item.value }}' dest='/etc/ansible/logs/manager.conf-{{ item.variable }}-{{ ansible_date_time.date }}-{{ ansible_hostname }}.log'
    with_items:
      - variable: difference
        value: '{{ difference }}'
    no_log: true

