# This playbook compares a specific file from two different hosts
# Example usage: ansible-playbook compare_pgbouncer.ini.yml

---
- name: Compare pgbouncer.ini file Playbook
  hosts: mas1_ip
  gather_facts: true

  tasks:
  - name: Fetch first pgbouncer.ini file
    fetch: dest=save/mas1_ip/pgbouncer.ini src=/opt/mcp/config/pgbouncer.ini flat=true validate_checksum=true

- hosts: mas2_ip
  gather_facts: true

  tasks:
  - name: Fetch second pgbouncer.ini file
    fetch: dest=save/mas2_ip/pgbouncer.ini src=/opt/mcp/config/pgbouncer.ini flat=true validate_checksum=true

- hosts: cm1
  gather_facts: true

  tasks:
  - name: 'Compare pgbouncer.ini files'
    command: 
      diff /etc/ansible/playbooks/monitor/save/mas1_ip/pgbouncer.ini /etc/ansible/playbooks/monitor/save/mas2_ip/pgbouncer.ini
      chdir=/etc/ansible/logs
    register: difference
    failed_when: difference.rc > 1
    changed_when: difference.rc == 1

  - name: Print differences
    debug: msg='{{ difference.stdout }}'

  - name: Create output file
    local_action: copy content='{{ item.value }}' dest='/etc/ansible/logs/pgbouncer.ini-{{ item.variable }}-{{ ansible_date_time.date }}-{{ ansible_hostname }}.log'
    with_items:
      - variable: difference
        value: '{{ difference }}'
    no_log: true

