# This playbook compares a specific file from two different hosts
# Example usage: ansible-playbook smsMcpKannel.conf.yml

---
- name: Compare smsMcpKannel.conf Playbook
  hosts: mas1_ip
  gather_facts: true

  tasks:
  - name: Fetch first smsMcpKannel.conf file
    fetch: dest=save/mas1_ip/smsMcpKannel.conf src=/opt/mcp/sms_receiver/config/smsMcpKannel.conf flat=true validate_checksum=true

- hosts: mas2_ip
  gather_facts: true

  tasks:
  - name: Fetch second smsMcpKannel.conf file
    fetch: dest=save/mas2_ip/smsMcpKannel.conf src=/opt/mcp/sms_receiver/config/smsMcpKannel.conf flat=true validate_checksum=true

- hosts: cm1
  gather_facts: true

  tasks:
  - name: 'Compare smsMcpKannel.conf files'
    command: 
      diff /etc/ansible/playbooks/monitor/save/mas1_ip/smsMcpKannel.conf /etc/ansible/playbooks/monitor/save/mas2_ip/smsMcpKannel.conf
      chdir=/etc/ansible/logs
    register: difference
    failed_when: difference.rc > 1
    changed_when: difference.rc == 1

  - name: Print differences
    debug: msg='{{ difference.stdout }}'ls

  - name: Create output file
    local_action: copy content='{{ item.value }}' dest='/etc/ansible/logs/smsMcpKannel.conf-{{ item.variable }}-{{ ansible_date_time.date }}-{{ ansible_hostname }}.log'
    with_items:
      - variable: difference
        value: '{{ difference }}'
    no_log: true

