---
- hosts: nano
  gather_facts: no
  become: yes
  tasks: 

       - name: check falstat   
         shell: /opt/mcp/falcon/fmc -v | grep "{{ item }}"
         register: output
         with_items: "{{ nanovars.falstat }}"
       - debug:
           msg: "{{ output }}"

       - name: copy output file 
         local_action: copy content='{{ item.value | list | to_nice_json }}' dest='/etc/ansible/logs/falstat' 
         with_items: 
             - variable: output.stdout_lines 
               value: "{{ output.results }}" 

       - name: mail the output
         mail: 
           to: "{{ nanovars.mail }}" 
           subject:  service is not running 
           body: service on $(hostname) is not running
         when: output.results | join('') | search('running', 'sls')

            
