     - name: Fetch .conf files
       fetch: dest=/etc/ansible/playbooks/movius/test_160/before_upgrade/{{ item }}/ src=/etc/asterisk/http.conf flat=true validate_checksum=true
       with_inventory_hostnames:
          - nano_server
       when: inventory_hostname == "{{ item }}" 
     - name: fetch
       fetch: dest=/etc/ansible/playbooks/movius/test_160/before_upgrade/{{ item }}/ src=/opt/mcp/config/scheduler.yml flat=true validate_checksum=true
       with_inventory_hostnames:
          - nano_server
       when: inventory_hostname == "{{ item }}"
     - name: fetch the files
       fetch: dest=/etc/ansible/playbooks/movius/test_160/before_upgrade/{{ item }}/ src=/opt/mcp/config/ha.yml flat=true validate_checksum=true
       with_inventory_hostnames:
          - nano_server
       when: inventory_hostname == "{{ item }}"
     - name: fetch the files
       fetch: dest=/etc/ansible/playbooks/movius/test_160/before_upgrade/{{ item }}/  src=/etc/asterisk/indications.conf flat=true validate_checksum=true
       with_inventory_hostnames:
          - nano_server
       when: inventory_hostname == "{{ item }}"
     - name: fetch the files
       fetch: dest=/etc/ansible/playbooks/movius/test_160/before_upgrade/{{ item }}/  src=/etc/asterisk/manager.conf flat=true validate_checksum=true
       with_inventory_hostnames:
          - nano_server
       when: inventory_hostname == "{{ item }}"
     - name: fetch the files
       fetch: dest=/etc/ansible/playbooks/movius/test_160/before_upgrade/{{ item }}/ src=/opt/mcp/courier/conf/mmail.conf flat=true validate_checksum=true
       with_inventory_hostnames:
          - nano_server
       when: inventory_hostname == "{{ item }}"
     - name: fetch the files
       fetch: dest=/etc/ansible/playbooks/movius/test_160/before_upgrade/{{ item }}/ src=/opt/mcp/config/pgbouncer.ini flat=true validate_checksum=true
       with_inventory_hostnames:
          - nano_server
       when: inventory_hostname == "{{ item }}"
     - name: fetch the files
       fetch: dest=/etc/ansible/playbooks/movius/test_160/before_upgrade/{{ item }}/ src=/opt/mcp/config/sms_gateway.yml flat=true validate_checksum=true
       with_inventory_hostnames:
          - nano_server
       when: inventory_hostname == "{{ item }}"
     - name: fetch the files
       fetch: dest=/etc/ansible/playbooks/movius/test_160/before_upgrade/{{ item }}/ src=/opt/mcp/sms_receiver/config/smsMcpKannel.conf flat=true validate_checksum=true
       with_inventory_hostnames:
          - nano_server
       when: inventory_hostname == "{{ item }}"
     - name: fetch the files
       fetch: dest=/etc/ansible/playbooks/movius/test_160/before_upgrade/{{ item }}/ src=/etc/asterisk/sip.conf flat=true validate_checksum=true
       with_inventory_hostnames:
          - nano_server
       when: inventory_hostname == "{{ item }}"
     - name: Fetch first mcp.yml file
       fetch: dest=/etc/ansible/playbooks/movius/test_160/before_upgrade/{{ item }}/ src=/opt/mcp/oamp-gui/config/mcp.yml flat=true validate_checksum=true
       with_inventory_hostnames:
          - nano_server
       when: inventory_hostname == "{{ item }}"
