    - name: check disk space before upgrade
      include: disk_space.yml
    - name: check falstat services before upgrade
      include: nano_falstat.yml
    - name: copy conf files before upgrade
      include: nano_bef_copy.yml
