---
- name: sss
  hosts: ansible
  gather_facts: no
  tasks:   

  - name: 'Compare ha.yml  files'
    command:
      diff /etc/ansible/playbooks/movius/test_160/before_upgrade/nano/ha.yml /etc/ansible/playbooks/movius/test_160/after_upgrade/{{ item }}/ha.yml
      chdir=/etc/ansible/playbooks/
    register: difference
    failed_when: difference.rc > 1
    changed_when: difference.rc == 1
    with_inventory_hostnames:
          - nano_server

  - name: Print differences
    debug: msg='{{ difference }}'

  - name: Create output file
    local_action: copy content='{{ item.value | list | to_nice_json }}' dest='/etc/ansible/nano_logs/compare/nano/ha.yml-{{ item.variable }}-{{ lookup('pipe','date \"+%Y-%m-%d %H:%M\"')}}-{{ inventory_hostname }}.log'
    register: output
    with_items:
          - variable: difference.stdout_lines
            value: "{{ difference.results }}"

  - name: copy output file
    local_action: copy content='{{ item.value | list | to_nice_json }}' dest='/etc/ansible/nano_logs/compare/nano/save/ha.yml.json'
    with_items:
          - variable: difference.stdout_lines
            value: "{{ difference.results }}"



  - name: send an email of compare files
    shell: mail -a "/etc/ansible/nano_logs/compare/nano/save/ha.yml.json" -s "nano_ha.yml"  "{{ myvars.mail }}"
