---
- name: check falstat for all servers
  hosts: cdr_servers
  gather_facts: no
  become: yes
  tasks:


       - name: falstat for spm
         shell: /opt/mcp/falcon/fmc -v | grep spm
         register: spm_output
       - name: print falstat
         debug:
           msg: "{{ spm_output }}"
       - name: mail the output
         mail:
           to: "{{ myvars.mail }}"
           subject: spm falstat is not running on {{ inventory_hostname }}
           body: "spm is not running on {{ inventory_hostname }}-{{ lookup('pipe','date \"+%Y-%m-%d %H:%M\"')}}"
         when:  "'stopped' in spm_output.stdout"

       - name: Create output file
         local_action: copy content='{{ item.value | to_nice_json }}' dest='/etc/ansible/uk3_logs/cdr/falstat/{{ item.variable }}-{{ lookup('pipe','date \"+%Y-%m-%d %H:%M\"')}}.log'
         register: output
         with_items:
           - variable: spm_output
             value: "{{ spm_output }}"


       - name: falstat for ptp
         shell: /opt/mcp/falcon/fmc -v | grep ptp
         register: ptp_output
       - name: print falstat
         debug:
           msg: "{{ ptp_output }}"
       - name: mail the output
         mail:
           to: "{{ myvars.mail }}"
           subject: ptp service is not running on {{ inventory_hostname }}
           body: "ptp service is not running on {{ inventory_hostname }}-{{ lookup('pipe','date \"+%Y-%m-%d %H:%M\"')}}"
         when:  "'stopped' in ptp_output.stdout"
       

       - name: Create output file
         local_action: copy content='{{ item.value | to_nice_json }}' dest='/etc/ansible/uk3_logs/cdr/falstat/{{ item.variable }}-{{ lookup('pipe','date \"+%Y-%m-%d %H:%M\"')}}.log'
         register: output
         with_items:
           - variable: ptp_output
             value: "{{ ptp_output }}"
        
       - name: falstat for httpd
         shell: /opt/mcp/falcon/fmc -v | grep httpd
         register: httpd_output
       - name: print falstat
         debug:
           msg: "{{ httpd_output }}"
       - name: mail the output
         mail:
           to: "{{ myvars.mail }}"
           subject: httpd service is not running on {{ inventory_hostname }}
           body: "httpd service is not running on {{ inventory_hostname }}-{{ lookup('pipe','date \"+%Y-%m-%d %H:%M\"')}}"
         when:  "'stopped' in httpd_output.stdout"

       - name: Create output file
         local_action: copy content='{{ item.value | to_nice_json }}' dest='/etc/ansible/uk3_logs/cdr/falstat/{{ item.variable }}-{{ lookup('pipe','date \"+%Y-%m-%d %H:%M\"')}}.log'
         register: output
         with_items:
           - variable: httpd_output
             value: "{{ httpd_output }}"
#       - name: pause the task
#         pause:
#         when: httpd_output.stdout | join('') | search('stopped')

       - name: falstat for imap
         shell: /opt/mcp/falcon/fmc -v | grep imap
         register: imap_output
       - name: print falstat
         debug:
           msg: "{{ imap_output }}"
       - name: mail the output
         mail:
           to: "{{ myvars.mail }}"
           subject: imap service is not running on {{ inventory_hostname }}
           body: "imap service is not running on {{ inventory_hostname }}-{{ lookup('pipe','date \"+%Y-%m-%d %H:%M\"')}}"
         when:  "'stopped' in imap_output.stdout"

       - name: Create output file
         local_action: copy content='{{ item.value | to_nice_json }}' dest='/etc/ansible/uk3_logs/cdr/falstat/{{ item.variable }}-{{ lookup('pipe','date \"+%Y-%m-%d %H:%M\"')}}.log'
         register: output
         with_items:
           - variable: imap_output
             value: "{{ imap_output }}"
 #      - name: pause the task
  #       pause:
   #      when: imap_output.stdout | join('') | search('stopped')

       - name: falstat for pgsql
         shell: /opt/mcp/falcon/fmc -v | grep pgsql
         register: pgsql_output
       - name: print falstat
         debug:
           msg: "{{ pgsql_output }}"
       - name: mail the output
         mail:
           to: "{{ myvars.mail }}"
           subject: pgsql service is not running on {{ inventory_hostname }}
           body: "pgsql service is not running on {{ inventory_hostname }}-{{ lookup('pipe','date \"+%Y-%m-%d %H:%M\"')}}"
         when:  "'stopped' in pgsql_output.stdout"


       - name: Create output file
         local_action: copy content='{{ item.value | to_nice_json }}' dest='/etc/ansible/uk3_logs/cdr/falstat/{{ item.variable }}-{{ lookup('pipe','date \"+%Y-%m-%d %H:%M\"')}}.log'
         register: output
         with_items:
           - variable: pgsql_output
             value: "{{ pgsql_output }}"
#       - name: pause the task
 #        pause:
  #       when: pgsql_output.stdout | join('') | search('stopped')
