---
- name: comapre etl.conf
  hosts: ansible
  gather_facts: yes
  vars_files: 
      - /etc/ansible/inventory/group_vars/all.yml
  tasks:
      - name: 'Compare etl.conf  files'
        shell:
           diff  /etc/ansible/playbooks/master/cdr/etl.conf /etc/ansible/playbooks/uk3/cdr/{{ item }}/etl.conf 
           chdir=/etc/ansible/playbooks/
        register: difference
        failed_when: difference.rc > 1
        changed_when: difference.rc == 1
        with_inventory_hostnames:
            - cdr_servers
    
   
      - name: use shell to print list of file paths
        debug: 
          msg: "{{ item.stdout_lines }}"
        with_items: "{{ difference.results }}"

      - name: Create output file
        local_action: copy content='{{ item.value | list | to_nice_json }}' dest='/etc/ansible/uk3_logs/cdr/etl.conf.json-{{ item.variable }}-{{ lookup('pipe','date \"+%Y-%m-%d %H:%M\"')}}-{{ ansible_hostname }}.log'
        with_items:
          - variable: difference.stdout_lines
            value: "{{ difference.results }}"

      - name: send an email on failure upgrade
        shell: mail -a "/etc/ansible/uk3_logs/cdr/etl.conf.json" -s "cdr_etl.conf"  "{{ myvars.mail }}"
        
  

     
