# This playbook executes multiple playbooks to compare specific files between two different hosts
# Example usage: ansible-playbook compare_master.yml

---
- name: Master config audit playbook
  hosts: ansible
  gather_facts: true

- include: mas_compare_sip.conf.yml
- include: mas_compare_mmail.conf.yml
- include: mas_compare_scheduler.yml.yml
- include: mas_compare_pgbouncer.ini.yml
- include: mas_compare_mcp.yml.yml
- include: mas_compare_manager.conf.yml
- include: mas_compare_http.conf.yml
- include: mas_compare_indications.conf.yml
- include: mas_compare_ha.yml.yml
- include: mas_compare_sms_gateway.yml.yml
- include: mas_compare_smsMcpkannel.conf.yml
