---
- name: check falstat for all servers
  hosts: userdb_servers
  gather_facts: yes
  become: yes
  tasks:


       - name: falstat for spm
         shell: /opt/mcp/falcon/fmc -v | grep spm
         register: spm_output
       - name: print falstat
         debug:
           msg: "{{ spm_output }}"
       - name: mail the output
         mail:
           to: vinnivanitha99@gmail.com
           subject: falstat
           body: spm is not running on {{ inventory_hostname }}
         when: spm_output.stdout | join('') | search('stopped')
       - name: pause the task
         pause:
         when: spm_output | join('') | search('stopped')

       - name: falstat for ptp
         shell: /opt/mcp/falcon/fmc -v | grep ptp
         register: ptp_output
       - name: print falstat
         debug:
           msg: "{{ ptp_output }}"
       - name: mail the output
         mail:
           to: vinnivanitha99@gmail.com
           subject: ptp service is not running
           body: ptp service is not running on {{ inventory_hostname }}
         when: ptp_output.stdout | join('') | search('stopped')
       - name: pause the task
         pause:
         when: ptp_output | join('') | search('stopped')

       - name: falstat for httpd
         shell: /opt/mcp/falcon/fmc -v | grep httpd
         register: httpd_output
       - name: print falstat
         debug:
           msg: "{{ httpd_output }}"
       - name: mail the output
         mail:
           to: vinnivanitha99@gmail.com
           subject: httpd service is not running
           body: httpd service is not running on {{ inventory_hostname }}
         when: httpd_output.stdout | join('') | search('stopped')
       - name: pause the task
         pause:
         when: httpd_output | join('') | search('stopped')

       - name: falstat for imap
         shell: /opt/mcp/falcon/fmc -v | grep imap
         register: imap_output
       - name: print falstat
         debug:
           msg: "{{ imap_output }}"
       - name: mail the output
         mail:
           to: vinnivanitha99@gmail.com
           subject: imap service is not running
           body: imap service is not running on {{ inventory_hostname }}
         when: imap_output.stdout | join('') | search('stopped')
       - name: pause the task
         pause:
         when: imap_output | join('') | search('stopped')

       - name: falstat for pgsql
         shell: /opt/mcp/falcon/fmc -v | grep pgsql
         register: pgsql_output
       - name: print falstat
         debug:
           msg: "{{ pgsql_output }}"
       - name: mail the output
         mail:
           to: vinnivanitha99@gmail.com
           subject: pgsql service is not running
           body: pgsql service is not running on {{ inventory_hostname }}
         when: pgsql_output.stdout | join('') | search('stopped')
       - name: pause the task
         pause:
         when: pgsql_output.stdout | join('') | search('stopped')
