# This playbook executes multiple playbooks to compare specific files between two different hosts
# Example usage: ansible-playbook compare_vapter.yml

---
- name: Master config audit playbook
  hosts: ansible
  gather_facts: true

- include: vap_compare_mmail.conf.yml
- include: vap_compare_scheduler.yml.yml
- include: vap_compare_pgbouncer.ini.yml
- include: vap_compare_manager.conf.yml
- include: vap_compare_http.conf.yml
- include: vap_compare_ha.yml.yml
- include: vap_compare_kamailio.cfg.yml
