---
- name: copy config files from cdr
  hosts: cdr1a
  gather_facts: no
  become: yes
  tasks:
     - name: fetch the conf file
       fetch: dest=/etc/ansible/playbooks/master/cdr/  src=/opt/mcp/config/sms.conf flat=true validate_checksum=true
     - name: fetch
       fetch: dest=/etc/ansible/playbooks/master/cdr/  src=/opt/mcp/config/scheduler.yml flat=true validate_checksum=true
     - name: fetch the files
       fetch: dest=/etc/ansible/playbooks/master/cdr/  src=/opt/mcp/config/ha.yml flat=true validate_checksum=true
     - name: fetch the files
       fetch: dest=/etc/ansible/playbooks/master/cdr/  src=/opt/mcp/config/pgbouncer.ini flat=true validate_checksum=true
     - name: fetch the files
       fetch: dest=/etc/ansible/playbooks/master/cdr/  src=/opt/mcp/courier/conf/mmail.conf flat=true validate_checksum=true
     - name: fetch the files
       fetch: dest=/etc/ansible/playbooks/master/cdr/  src=/opt/cdrtool/etc/etl.conf flat=true validate_checksum=true
     - name: fetch the files
       fetch: dest=/etc/ansible/playbooks/master/cdr/  src=/opt/cdrtool/etc/webapi.conf flat=true validate_checksum=true
     - name: fetch the files
       fetch: dest=/etc/ansible/playbooks/master/cdr/  src=/opt/mcp/billing/billing.conf flat=true validate_checksum=true
     - name: fetch the files
       fetch: dest=/etc/ansible/playbooks/master/cdr/  src=/opt/mcp/billing/billing.sh flat=true validate_checksum=true
     - name: fetch the files
       fetch: dest=/etc/ansible/playbooks/master/cdr/  src=/opt/cdrtool/etc/cdr_offload_filter flat=true validate_checksum=true
     - name: fetch the files
       fetch: dest=/etc/ansible/playbooks/master/cdr/  src=/opt/opennms/etc/opennms.properties flat=true validate_checksum=true
     
