---
- name: copy conf files before upgrade
  hosts: vap1
  gather_facts: no
  tasks:
     - name: Fetch the files
       fetch: dest=/etc/ansible/playbooks/master/vap/  src=/usr/local/etc/kamailio/kamailio.cfg flat=true validate_checksum=true
     - name: Fetch .conf files
       fetch: dest=/etc/ansible/playbooks/master/vap/  src=/etc/asterisk/http.conf flat=true validate_checksum=true
     - name: fetch
       fetch: dest=/etc/ansible/playbooks/master/vap/  src=/opt/mcp/config/scheduler.yml flat=true validate_checksum=true
     - name: fetch the files
       fetch: dest=/etc/ansible/playbooks/master/vap/  src=/opt/mcp/config/ha.yml flat=true validate_checksum=true
     - name: fetch the files
       fetch: dest=/etc/ansible/playbooks/master/vap/  src=/etc/asterisk/manager.conf flat=true validate_checksum=true
     - name: fetch the files
       fetch: dest=/etc/ansible/playbooks/master/vap/  src=/opt/mcp/courier/conf/mmail.conf flat=true validate_checksum=true
     - name: fetch the files
       fetch: dest=/etc/ansible/playbooks/master/vap/  src=/opt/mcp/config/pgbouncer.ini flat=true validate_checksum=true
     - name: Fetch first regex_groups file
       fetch: dest=/etc/ansible/playbooks/master/vap/ src=/usr/local/etc/kamailio/regex_groups flat=true validate_checksum=true
     - name: Fetch first regex_groups file
       fetch: dest=/etc/ansible/playbooks/master/vap/ src=/etc/sysconfig/ha/lvs.cf flat=true validate_checksum=true
      
