---
- hosts: localhost
  vars:
    http_port: 80
    max_clients: 200
  remote_user: root
  tasks:
  - name: ensure apache is at the latest version
#    service: name=httpd state=stopped
    service: name=httpd state=started
#    service: name=httpd state=restarted
#    notify:
#    - restart httpd
