
---
- hosts: all
  gather_facts: true
  tasks:
   - name: Upgrade all the mas servers
#     command: pm_util -c upgrade {{ansible_hostname}} -s MCP-3.4.{{ mcp_version }}
     command: ifconfig
     delegate_to: local_152
     register: myname

   - name: Print myname
     debug: msg="{{ myname.stdout }}"
