---
- name: Compare pgbouncer.ini file Playbook

  hosts: ansible
  gather_facts: true

  tasks:
  - name: 'Compare pgbouncer.ini files'
    command:
      diff /root/config/before_upgrade/cdb/pgbouncer.ini /root/config/after_upgrade/cdb/pgbouncer.ini
      chdir=/root/config/
    register: difference
    failed_when: difference.rc > 1
    changed_when: difference.rc == 1

  - name: Print differences
    debug: msg='{{ difference.stdout }}'

  - name: Create output file
    local_action: copy content='{{ item.value }}' dest='/etc/ansible/logs/pgbouncer.ini-{{ item.variable }}-{{ ansible_date_time.date }}-{{ ansible_hostname }}.log'
    with_items:
      - variable: difference
        value: '{{ difference }}'
    no_log: true
