---
- name: Compare mcp.yml file Playbook
  hosts: ansible
  gather_facts: true

  tasks:
  - name: 'Compare mcp.yml files'
    command: 
      diff /root/config/before_upgrade/mas1/mcp.yml /root/config/after_upgrade/mas1/mcp.yml
      chdir=/root/config/
    register: difference
    failed_when: difference.rc > 1
    changed_when: difference.rc == 1

  - name: Print differences
    debug: msg='{{ difference.stdout }}'

  - name: Create output file
    local_action: copy content='{{ item.value }}' dest='/etc/ansible/logs/mcp.yml-{{ item.variable }}-{{ ansible_date_time.date }}-{{ ansible_hostname }}.log'
    with_items:
      - variable: difference
        value: '{{ difference }}'
    no_log: true

