---
- name: Compare regex_groups file Playbook
  hosts: ansible
  gather_facts: true

  tasks:
  - name: 'Compare regex_groups files'
    command: 
      diff /root/config/before_upgrade/vap1/regex_groups /root/config/after_upgrade/vap1/regex_groups 
      chdir=/root/config/
    register: difference
    failed_when: difference.rc > 1
    changed_when: difference.rc == 1

  - name: Print differences
    debug: msg='{{ difference.stdout }}'

  - name: Create output file
    local_action: copy content='{{ item.value }}' dest='/etc/ansible/logs/regex_groups-{{ item.variable }}-{{ ansible_date_time.date }}-{{ ansible_hostname }}.log'
    with_items:
      - variable: difference
        value: '{{ difference }}'
    no_log: true
