---
- name: Compare manager.conf file Playbook
  hosts: ansible
  gather_facts: true

  tasks:
  - name: 'Compare manager.conf files'
    command: 
      diff /root/config/before_upgrade/vap1/manager.conf /root/config/after_upgrade/vap1/manager.conf 
      chdir=/root/config/
    register: difference
    failed_when: difference.rc > 1
    changed_when: difference.rc == 1

  - name: Print differences
    debug: msg='{{ difference.stdout }}'
  
  - name: Create output file
    local_action: copy content='{{ item.value }}' dest='/etc/ansible/logs/manager.conf-{{ item.variable }}-{{ ansible_date_time.date }}-{{ ansible_hostname }}.log'
    with_items:
      - variable: difference
        value: '{{ difference }}'
    no_log: true

