---
- name: compare ha.yml
  hosts: ansible
  gather_facts: yes

  tasks:
   - name: 'Compare ha.yml files'
     command: 
       diff /root/config/before_upgrade/vap2/ha.yml /root/config/after_upgrade/vap2/ha.yml
       chdir=/root/config/
     register: difference
     failed_when: difference.rc > 1
     changed_when: difference.rc == 1
   - name: Print differences
     debug: msg='{{ difference.stdout }}'


   - name: Create output file
     local_action: copy content='{{ item.value }}' dest='/etc/ansible/logs/ha.yml-{{ item.variable }}-{{ ansible_date_time.date }}-{{ ansible_hostname }}.log'
     with_items:
      - variable: difference
        value: '{{ difference }}'
     no_log: true
