---
- hosts: ansible
  gather_facts: true

  tasks:
  - name: 'Compare indications.conf files'
    command: 
      diff /root/config/before_upgrade/vap2/indications.conf /root/config/after_upgrade/vap2/indications.conf
      chdir=/root/config/
    register: difference
    failed_when: difference.rc > 1
    changed_when: difference.rc == 1
