#This playbook executes multiple playbooks to copy specific files between different hosts
# Example usage: ansible-playbook master_copy.yml

---
- name: Master config audit playbook
  hosts: mas_servers,db_servers,cdr_servers,userdb_servers,vap_servers
  gather_facts: no
  become: yes


- include: mas_copy.yml
- include: db_copy.yml
- include: cdr_copy.yml
- include: userdb_copy.yml
- include: vap_copy.yml
