---
- name: 'Compare scheduler.yml  files'
  hosts: ansible
  gather_facts: yes
  tasks:
      - name: 'Compare scheduler.yml  files'
        command:
           diff /etc/ansible/playbooks/master/db/scheduler.yml /etc/ansible/playbooks/uk3/db/{{ item }}/scheduler.yml
           chdir=/etc/ansible/playbooks/
        register: difference
        failed_when: difference.rc > 1
        changed_when: difference.rc == 1
        with_inventory_hostnames:
          - db_servers

      - name: print output
        debug:
          msg: "{{ item.stdout_lines }}"
        with_items: "{{ difference.results }}"

      - name: Create output file
        local_action: copy content='{{ item.value | list | to_nice_json }}' dest='/etc/ansible/uk3_logs/db/scheduler.yml.json-{{ item.variable }}-{{ lookup('pipe','date \"+%Y-%m-%d %H:%M\"')}}-{{ ansible_hostname }}.log'
        register: output
        with_items:
          - variable: difference.stdout_lines
            value: "{{ difference.results }}"

      - name: copy output file
        local_action: copy content='{{ item.value | list | to_nice_json }}' dest='/etc/ansible/uk3_logs/db/save/scheduler.yml.json'
        with_items:
          - variable: difference.stdout_lines
            value: "{{ difference.results }}"


      - name: send an email on failure upgrade
        shell: mail -a "/etc/ansible/uk3_logs/db/save/scheduler.yml.json" -s "db_scheduler.yml"  "{{ myvars.mail }}"
