# This playbook executes multiple playbooks to compare specific files between two different hosts
# Example usage: ansible-playbook compare_master.yml

---
- name: Master config audit playbook
  hosts: ansible
  gather_facts: true

- include: compare_mmail.conf.yml
- include: compare_scheduler.yml.yml
- include: compare_pgbouncer.ini.yml
- include: compare_ha.yml.yml
- include: compare_sms.conf.yml
- include: compare_etl.conf.yml
