---
- name: copy config files from db
  hosts: db_servers
  gather_facts: no
  become: yes
  tasks:
     - name: fetch the conf file
       fetch: dest=/etc/ansible/playbooks/movius/upgrade/before_upgrade/db/{{ item }}/ src=/opt/mcp/config/sms.conf flat=true validate_checksum=true
       with_inventory_hostnames:
          - db_servers
       when: inventory_hostname == "{{ item }}"
     - name: fetch
       fetch: dest=/etc/ansible/playbooks/movius/upgrade/before_upgrade/db/{{ item }}/ src=/opt/mcp/config/scheduler.yml flat=true validate_checksum=true
       with_inventory_hostnames:
          - db_servers
       when: inventory_hostname == "{{ item }}"
     - name: fetch the files
       fetch: dest=/etc/ansible/playbooks/movius/upgrade/before_upgrade/db/{{ item }}/ src=/opt/mcp/config/ha.yml flat=true validate_checksum=true
       with_inventory_hostnames:
          - db_servers
       when: inventory_hostname == "{{ item }}"
     - name: fetch the files
       fetch: dest=/etc/ansible/playbooks/movius/upgrade/before_upgrade/db/{{ item }}/ src=/opt/mcp/config/pgbouncer.ini flat=true validate_checksum=true
       with_inventory_hostnames:
          - db_servers
       when: inventory_hostname == "{{ item }}"
     - name: fetch the files
       fetch: dest=/etc/ansible/playbooks/movius/upgrade/before_upgrade/db/{{ item }}/ src=/opt/mcp/courier/conf/mmail.conf flat=true validate_checksum=true
       with_inventory_hostnames:
          - db_servers
       when: inventory_hostname == "{{ item }}"
     - name: fetch the files
       fetch: dest=/etc/ansible/playbooks/movius/upgrade/before_upgrade/db/{{ item }}/ src=/opt/cdrtool/etc/etl.conf flat=true validate_checksum=true
       with_inventory_hostnames:
          - db_servers
       when: inventory_hostname == "{{ item }}"
     - name: fetch the files
       fetch: dest=/etc/ansible/playbooks/movius/upgrade/before_upgrade/db/{{ item }}/ src=/opt/cdrtool/etc/webapi.conf flat=true validate_checksum=true
       with_inventory_hostnames:
          - db_servers
       when: inventory_hostname == "{{ item }}"
     
