---
- name: copy conf files before upgrade
  hosts: mas1
  gather_facts: no
  tasks:
     - name: Fetch .conf files
       fetch: dest=/etc/ansible/playbooks/master/mas/  src=/etc/asterisk/http.conf flat=true validate_checksum=true
     - name: fetch
       fetch: dest=/etc/ansible/playbooks/master/mas/  src=/opt/mcp/config/scheduler.yml flat=true validate_checksum=true
     - name: fetch the files
       fetch: dest=/etc/ansible/playbooks/master/mas/  src=/opt/mcp/config/ha.yml flat=true validate_checksum=true
     - name: fetch the files
       fetch: dest=/etc/ansible/playbooks/master/mas/   src=/etc/asterisk/indications.conf flat=true validate_checksum=true
     - name: fetch the files
       fetch: dest=/etc/ansible/playbooks/master/mas/   src=/etc/asterisk/manager.conf flat=true validate_checksum=true
     - name: fetch the files
       fetch: dest=/etc/ansible/playbooks/master/mas/  src=/opt/mcp/courier/conf/mmail.conf flat=true validate_checksum=true
     - name: fetch the files
       fetch: dest=/etc/ansible/playbooks/master/mas/  src=/opt/mcp/config/pgbouncer.ini flat=true validate_checksum=true
     - name: fetch the files
       fetch: dest=/etc/ansible/playbooks/master/mas/  src=/opt/mcp/config/sms_gateway.yml flat=true validate_checksum=true
     - name: fetch the files
       fetch: dest=/etc/ansible/playbooks/master/mas/  src=/opt/mcp/sms_receiver/config/smsMcpKannel.conf flat=true validate_checksum=true
     - name: fetch the files
       fetch: dest=/etc/ansible/playbooks/master/mas/  src=/etc/asterisk/sip.conf flat=true validate_checksum=true
     - name: Fetch first mcp.yml file
       fetch: dest=/etc/ansible/playbooks/master/mas/  src=/opt/mcp/oamp-gui/config/mcp.yml flat=true validate_checksum=true
