---
- name: copy conf files before upgrade
  hosts: mas_servers
  gather_facts: no
  tasks:
     - name: Fetch .conf files
       fetch: dest=/etc/ansible/playbooks/uk3/mas/{{ item }}/ src=/etc/asterisk/http.conf flat=true validate_checksum=true
       with_inventory_hostnames:
          - mas_servers
       when: inventory_hostname == "{{ item }}" 
     - name: fetch
       fetch: dest=/etc/ansible/playbooks/uk3/mas/{{ item }}/ src=/opt/mcp/config/scheduler.yml flat=true validate_checksum=true
       with_inventory_hostnames:
          - mas_servers
       when: inventory_hostname == "{{ item }}"
     - name: fetch the files
       fetch: dest=/etc/ansible/playbooks/uk3/mas/{{ item }}/ src=/opt/mcp/config/ha.yml flat=true validate_checksum=true
       with_inventory_hostnames:
          - mas_servers
       when: inventory_hostname == "{{ item }}"
     - name: fetch the files
       fetch: dest=/etc/ansible/playbooks/uk3/mas/{{ item }}/  src=/etc/asterisk/indications.conf flat=true validate_checksum=true
       with_inventory_hostnames:
          - mas_servers
       when: inventory_hostname == "{{ item }}"
     - name: fetch the files
       fetch: dest=/etc/ansible/playbooks/uk3/mas/{{ item }}/  src=/etc/asterisk/manager.conf flat=true validate_checksum=true
       with_inventory_hostnames:
          - mas_servers
       when: inventory_hostname == "{{ item }}"
     - name: fetch the files
       fetch: dest=/etc/ansible/playbooks/uk3/mas/{{ item }}/ src=/opt/mcp/courier/conf/mmail.conf flat=true validate_checksum=true
       with_inventory_hostnames:
          - mas_servers
       when: inventory_hostname == "{{ item }}"
     - name: fetch the files
       fetch: dest=/etc/ansible/playbooks/uk3/mas/{{ item }}/ src=/opt/mcp/config/pgbouncer.ini flat=true validate_checksum=true
       with_inventory_hostnames:
          - mas_servers
       when: inventory_hostname == "{{ item }}"
     - name: fetch the files
       fetch: dest=/etc/ansible/playbooks/uk3/mas/{{ item }}/ src=/opt/mcp/config/sms_gateway.yml flat=true validate_checksum=true
       with_inventory_hostnames:
          - mas_servers
       when: inventory_hostname == "{{ item }}"
     - name: fetch the files
       fetch: dest=/etc/ansible/playbooks/uk3/mas/{{ item }}/ src=/opt/mcp/sms_receiver/config/smsMcpKannel.conf flat=true validate_checksum=true
       with_inventory_hostnames:
          - mas_servers
       when: inventory_hostname == "{{ item }}"
     - name: fetch the files
       fetch: dest=/etc/ansible/playbooks/uk3/mas/{{ item }}/ src=/etc/asterisk/sip.conf flat=true validate_checksum=true
       with_inventory_hostnames:
          - mas_servers
       when: inventory_hostname == "{{ item }}"
     - name: Fetch first mcp.yml file
       fetch: dest=/etc/ansible/playbooks/uk3/mas/{{ item }}/ src=/opt/mcp/oamp-gui/config/mcp.yml flat=true validate_checksum=true
       with_inventory_hostnames:
          - mas_servers
       when: inventory_hostname == "{{ item }}"
