---
- hosts: ansible
  tasks:
    - name: Ensuring that free space on '/' is grater than 30%
      assert:
        that:
           not {{ item.mount == "/" and ( item.size_available < item.size_total - ( item.size_total|float * 0.3 ) ) }}
      with_items: "{{ ansible_mounts }}"
      ignore_errors: yes
      register: disk_free
    - debug: var=disk_free
