---
- hosts: ansible
  gather_facts: no
  tasks:

  - name: test for available disk space
    assert:
    that: 
    - not {{ item.mount == '{{ / }}' and ( item.size_available < item.size_total - ( item.size_total|float * 0.7 ) ) }}
    with_items: '{{ansible_mounts}}'
    ignore_errors: yes
    register: disk_free

  - name: Fail the play
    fail: msg="disk space has reached 70% threshold"
    when: disk_free|failed
