   - block:

     - name: add software
       command: spm_util -c addsw -f /root/builds/3.4/MCP-3.4.110-67.tar
       register: software_output 

     rescue:

     - name: send mail
       mail:
         to: vinnivanitha99@gmail.com
         subject: adding software is failed
         body: adding software to repository is failed
         when: software_output is failed

     - name: pause the task
       meta: end_play
       when: software_output is failed
   
  

