       - name: falstat for sls  
         shell: /opt/mcp/falcon/fmc -v | grep sls
         register: sls_output
       - name: print falstat
         debug: 
           msg: "{{ sls_output }}"
       - name: mail the output
         mail:
           to: vinnivanitha99@gmail.com
           subject: sls service is not running
           body: sls service on $(hostname) is not running 
         when: sls_output.stdout | join('') | search('stopped')
       - name: pause the task
         pause:
         when: sls_output.stdout | join('') | search('stopped')

       - name: falstat for spm
         shell: /opt/mcp/falcon/fmc -v | grep spm
         register: spm_output
       - name: print falstat
         debug:
           msg: "{{ spm_output }}"
       - name: mail the output
         mail:
           to: vinnivanitha99@gmail.com
           subject: falstat
           body: falsfat
         when: spm_output.stdout | join('') | search('stopped')
       - name: pause the task
         pause:
         when: spm_output.stdout | join('') | search('stopped')

 
       - name: falstat for httpd
         shell: /opt/mcp/falcon/fmc -v | grep httpd
         register: httpd_output
       - name: print falstat
         debug:
           msg: "{{ httpd_output }}"
       - name: mail the output
         mail:
           to: vinnivanitha99@gmail.com
           subject: httpd service is not running
           body: httpd service is not running on $(hostname)
         when: httpd_output.stdout | join('') | search('stopped')
       - name: pause the task
         pause:
         when: httpd_output.stdout | join('') | search('stopped')
