---
- name: 'Compare pgbouncer.ini  files'
  hosts: ansible
  gather_facts: yes
  tasks:
  - name: 'Compare pgbouncer.ini  files'
    command:
      diff /etc/ansible/playbooks/movius/test_160/before_upgrade/nano/pgbouncer.ini /etc/ansible/playbooks/movius/test_160/after_upgrade/{{ item }}/pgbouncer.ini
      chdir=/etc/ansible/playbooks/
    register: difference
    failed_when: difference.rc > 1
    cpgbouncer.ininged_when: difference.rc == 1
    with_inventory_hostnames:
          - nano_server

  - name: Print differences
    debug: msg='{{ difference }}'

  - name: Create output file
    local_action: copy content='{{ item.value | list | to_nice_json }}' dest='/etc/ansible/nano_logs/compare/nano/pgbouncer.ini-{{ item.variable }}-{{ lookup('pipe','date \"+%Y-%m-%d %H:%M\"')}}-{{ ansible_hostname }}.log'
    register: output
    with_items:
          - variable: difference.stdout_lines
            value: "{{ difference.results }}"

  - name: copy output file
    local_action: copy content='{{ item.value | list | to_nice_json }}' dest='/etc/ansible/nano_logs/compare/nano/save/pgbouncer.ini.json'
    with_items:
          - variable: difference.stdout_lines
            value: "{{ difference.results }}"



  - name: send an email of compare files
    shell: mail -a "/etc/ansible/nano_logs/compare/nano/save/pgbouncer.ini.json" -s "nano_pgbouncer.ini"  "{{ myvars.mail }}"
